## NUMPY

Matematiksel fonksiyonların olduğu kütüphanedir. Hızlı numerik işlemler için kullanılır.


*   Tek boyutlu array olabilir ama matrix olamaz.
*   İki boyutlu array lere matrix denir.


*   Numpy Array ler homojen olmalı(aynı tipte veriler).
*  



In [2]:
import numpy as np

In [ ]:
sinus = np.sin(np.pi/2)

## Array yaratmak


Python listlerine benzeyen, ancak farklı veri tiplerinde eleman içeremez aynı tipten çok sayıda elemanı içeren, hızlı işlem yapılmasını sağlayan kavramlardır.

In [ ]:
x= np.array([1,2,3,4])

In [ ]:
x

array([1, 2, 3, 4])

In [ ]:
type(x)

numpy.ndarray

In [ ]:
m= np.array(["a","b","c"])

In [ ]:
m

array(['a', 'b', 'c'], dtype='<U1')

In [ ]:
## eğer arrayin içinde bir tane bile karakter varsa; elemanlar, arrayın içinde string tipinde tutulur.
n= np.array([1,2,3,2.5,"a"])

In [ ]:
n

array(['1', '2', '3', '2.5', 'a'], dtype='<U32')

In [ ]:
# Bir tane float olduğu için dğer integerlar da floata dönüştü
z= np.array([1,2,3,3.5])

In [ ]:
z

array([1. , 2. , 3. , 3.5])

In [ ]:
# String değer içerdiğinden diğer elemanlar da string veri tipine cast edilir
c=np.array(['30',20,64,"s",6.2])
c

array(['30', '20', '64', 's', '6.2'], dtype='<U32')

## Array data tipini belirleme

In [ ]:
x=np.array([1,2,3.4]) # veriler genel olana cast edilir integar lar float a döner

In [ ]:
x

array([1. , 2. , 3.4])

In [ ]:
x=np.array([1,2,3.6], dtype="int32")   #arrayin tipini integer yapma

In [ ]:
x

array([1, 2, 3], dtype=int32)

In [ ]:
y=np.array([1,2,3.4], dtype="str") #arrayin tipini str yapma

In [ ]:
y

array(['1', '2', '3.4'], dtype='<U3')

In [ ]:
y=np.array([1,2,"a"], dtype="int32")  #str olduğu için integer hale getiremeyiz.

ValueError: invalid literal for int() with base 10: 'a'

In [ ]:
#String halinde yazılmış float floata cast edilebilir
z = np.array(["5.2"], dtype = "float")

In [ ]:
z

array([5.2])

In [ ]:
#String şeklinde yazılmış integer integar a cast edilebilir
z = np.array(["5"], dtype = "int32")

In [ ]:
z

array([5], dtype=int32)

In [ ]:
#String biçiminde yazılmış float direkt integer a cast edilemez
z = np.array(["5.2"], dtype = "int32")

ValueError: invalid literal for int() with base 10: '5.2'

## Elemanları 0 olan array

In [ ]:
c= np.zeros(10) #kaç elemanlı 0 dan oluşan array istersin
c

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros(10, dtype = str )

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U1')

# Elemanları 0 dan oluşan **multidimensional** array oluşturma

In [ ]:
#3 satır(row) ve 5 sütun(kolon)
a=np.zeros((3,5)) #paranteze dikkat. Shape ve data type beklediği için () veya [] kullanmalısın

In [ ]:
# 2 boyutlu 3x5 lik array = matris
x= np.zeros([3,5]) #köşeli paranteze dikkat
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
# 3 boyutlu = tensor
# 4 tane 5x7 lik array kur
y= np.zeros([4,5,7])
y

array([[[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]]])

In [ ]:
np.zeros(2, dtype = int)

array([0, 0])

In [ ]:
np.zeros((1,2), dtype = int) #Multidimensional array de data tipi belirtme

array([[0, 0]])

In [ ]:
# four-dimensional NumPy array (tensor) filled with zeros
# 2 blocks, where each block contains 4 rows, 4 columns, and 5 elements in the innermost dimension
x=np.zeros([2,4,4,5])
x

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0

## array bilgilerine erişme

In [ ]:
c.shape #boyutuna erişme

(10,)

In [ ]:
c.ndim

1

In [ ]:
a.shape

(3, 5)

In [ ]:
a.ndim

2

In [ ]:
x.shape

(3, 5)

In [ ]:
y.shape

(4, 5, 7)

In [ ]:
c.ndim

1

In [ ]:
a.ndim

2

In [ ]:
#boyut
x.ndim

2

In [ ]:
#boyut
y.ndim

3

In [ ]:
#array içindeki eleman (3*5)
x.size

15

In [ ]:
# 4*5*7
y.size


140

## Belirtilen bir elemandan array oluşturma : **np.full()**

In [ ]:
# 3x5 lik elemanları 7 olan array
np.full((3,5),7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [ ]:
np.full((3,5),7, dtype="int32")

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]], dtype=int32)

In [ ]:
np.full((3,5),"m")

array([['m', 'm', 'm', 'm', 'm'],
       ['m', 'm', 'm', 'm', 'm'],
       ['m', 'm', 'm', 'm', 'm']], dtype='<U1')

In [ ]:
np.full((4,5), 5.6, dtype= "str") #5.2 önce integar a cast oluyor sonra string şeklinde dönüştürülüyor

array([['5', '5', '5', '5', '5'],
       ['5', '5', '5', '5', '5'],
       ['5', '5', '5', '5', '5'],
       ['5', '5', '5', '5', '5']], dtype='<U1')

In [ ]:
np.full((4,5),"5.2")

array([['5.2', '5.2', '5.2', '5.2', '5.2'],
       ['5.2', '5.2', '5.2', '5.2', '5.2'],
       ['5.2', '5.2', '5.2', '5.2', '5.2'],
       ['5.2', '5.2', '5.2', '5.2', '5.2']], dtype='<U3')

In [ ]:
np.full(2,3) # 1-dimensional array with 2 elements, each filled with the value 3.

array([3, 3])

## Ardışık Sayılardan Array Oluşturmak: **np.arange()**

In [ ]:
np.arange(0,12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
np.arange(0,14,2) # 2 atlamalı şekilde 14'e kadar array oluşturdu

array([ 0,  2,  4,  6,  8, 10, 12])

In [ ]:
np.arange(2,12,-2) # 2 den 12 ye -2 gidemez bu yüzden boş array

array([], dtype=int64)

## Aralığı Eşit Uzaklıktaki Noktalara Bölerek Array Oluşturma: **np.linespace()**

Verilen başlangıç ve bitiş noktasına göre, başlangıç ve bitiş noktası da dahil aradaki sayıları eşit uzaklıkta olacak şekilde yazarak oluşturur.

In [ ]:
#default olarak aradaki mesafeyi 50 nokta olacak şekilde yazar
np.linspace(1,2)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [ ]:
np.linspace(1,2).ndim

1

### Kaç Parçaya Bölüneceğini Belirleme

In [ ]:
#num=3 ile 1-2 arasındaki mesafeyi kendileri dahil 3'e bölüyor.
np.linspace(1,2,num=3)

array([1. , 1.5, 2. ])

In [ ]:
#np.linespace(start,stop,step) şeklinde gider num diye belirtmesen de olur.
np.linspace(1.5,3,3)

array([1.5 , 2.25, 3.  ])

## Normal Distibution'dan Çekilmiş Değerler ile Array Oluşturma

 **np.random.normal(mean, std, array shape)**

In [ ]:
np.random.normal(0,1, (3,5)) #0 ortalamalı, standart sapması 1 olacak şekilde (3x5)lik
#bir normal dağılıma uygun array oluşturduk

array([[ 0.22753338,  0.61759578, -2.08359809,  0.36115503, -0.28057289],
       [-1.45751551,  0.12881301, -0.92069119,  1.71970581,  0.60201386],
       [ 0.22370532,  1.24464806, -0.1511746 ,  1.6987345 , -0.60388346]])

In [ ]:
np.random.normal(0,100, (3,5))

array([[   1.34359502,   15.43204244, -119.19738755, -101.18570808,
        -207.78771138],
       [ 131.24975935,  -30.06219663, -143.52951783,   75.06859769,
        -137.99573634],
       [-146.83945202, -104.59524868,  133.31050658, -185.80177234,
          60.0273064 ]])

## Random Integer lar ile Array Oluşturmak: **np.random.randint(low, high)**

In [ ]:
# np.random.randint(low,high)
# 15 dahil değil
# uniform distribution kullanılarak seçim yapılıyor

np.random.randint(1,15,(3,5))

array([[11,  1,  1,  4, 10],
       [ 5,  9,  5,  8,  7],
       [ 5,  2, 12, 14,  9]])

In [ ]:

np.random.randint(5,15,(3,5))

array([[12,  8,  5,  7, 12],
       [ 9, 12,  9, 13, 11],
       [ 7, 14,  8,  9, 11]])

In [ ]:
np.random.randint(1,10,(3,5,4)) # 3 tane 5 x 4 lük 1 den 10 a kadar sayılarla

array([[[3, 3, 1, 5],
        [3, 3, 8, 9],
        [2, 3, 2, 6],
        [9, 6, 1, 7],
        [5, 6, 3, 4]],

       [[9, 7, 2, 8],
        [1, 1, 7, 5],
        [9, 4, 4, 9],
        [7, 3, 1, 9],
        [2, 1, 3, 9]],

       [[7, 4, 2, 7],
        [6, 8, 5, 4],
        [1, 2, 4, 1],
        [2, 1, 5, 2],
        [7, 9, 1, 1]]])

In [ ]:
np.random.randint(1,10) #random olarak sayı üretme

1

In [ ]:
 #how to generate random integers and count their occurrences
d = {} #to store the counts of each generated random integer.

for _ in range(2000):
  val =  np.random.randint(1,11)

  if val not in d:
    d[val] = 1
  else:
    d[val] += 1

print(d)


{5: 212, 4: 202, 7: 200, 2: 200, 6: 197, 8: 184, 10: 200, 3: 213, 1: 186, 9: 206}


##Identity (Birim) Matrix : **np.eye()**

Identity Matrix ile başka matrixi çarınca aynı matrix olur.

In [ ]:
# birim array yaratma (köşegenleri 1 olan diğer elemanları 0 olan array)
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

# Array Matematiksel İşlemler

In [ ]:
#list ile integer çarpma işlemi concatenation olur. Consecutive concatenation
[2,3,4] * 3

In [ ]:
#note: listede toplama işlemi tanımlı değil
[1,2,3] + [4,5,6]

In [ ]:
#list ile list çarpımı olmaz
[2,3,4] * [2,3,4]

In [ ]:
x= np.array([1,2,3])
y= np.array([4,5,6])

In [ ]:
x

array([1, 2, 3])

In [ ]:
x * 2 #x in her elemanı 2 ile çarpılır

array([2, 4, 6])

In [ ]:
x*y # numpy array leri elementwise çarpım yapar

array([ 4, 10, 18])

In [ ]:
x+y # numpy arrayleri elementwise toplama yapar

array([5, 7, 9])

In [ ]:
print(x+y)

[5 7 9]


In [ ]:
x= np.array([1,2,3])
y= np.array([4,5,6,8])

x*y  #(arraylar birbirine denk olmadığı için hata aldık)

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [ ]:
a= np.array([    [1,2,3],[4,5,6]      ])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a*a

array([[ 1,  4,  9],
       [16, 25, 36]])

In [ ]:
a+a

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [ ]:
a/a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
a*3

array([[ 3,  6,  9],
       [12, 15, 18]])

In [ ]:
a+5

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
a.shape

(2, 3)

In [ ]:
#matris gibi çarpım yapar. (dot) (shapelerin aynı olmasına gerek yoktur)

a1 = np.array([[1,2],
               [2,0],
               [3,1]])

a2 = np.array ([[4,3],
                [1,2]])

print(np.dot(a1,a2))


##Array Attributes

###**shape**: array in dimensionları verir

In [ ]:
x1 = np.zeros((3,5))
x1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
x2 = np.zeros((2,3,4))
print(x2)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [ ]:
x1.shape


(3, 5)

In [ ]:
x2.shape

(2, 3, 4)

###**ndim**: array kaç dimension var

In [ ]:
x1.ndim

2

In [ ]:
x2.ndim

3

In [ ]:
#her bir değerin karekökünü aldı
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

###**size**: array in boyutunu, kaç elemanlı olduğunu gösterir

In [ ]:
x1.size

15

In [ ]:
x2.size

24

###**dtype**: array in veri tipini gösterir

In [ ]:
x1.dtype

dtype('float64')

## Reshape

Önemli olan reshape yapacağımız yapının yaptıktan sonraki yapıyla eleman sayısının (size) aynı olmalı.

In [ ]:
m=np.arange(1,11)
m

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
new_m = m.reshape(2,5) # 2*5 = 10 olduğundan ve 10=m olduğundan hatasız çalışır
new_m

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
m.ndim

1

In [ ]:
new_m.ndim #boyut değişimi (reshape) yapıldı

2

In [ ]:
m.reshape(3,5) #3*5= 15 olduğundan 15 != m olduğundan hata aldık. Array 1 den 11 e kadar ayarlanmıştı.

ValueError: cannot reshape array of size 10 into shape (3,5)

In [ ]:
# eleman sayısı ile reshape içindeki (satır * sütunun) aynısı olması gerekldiri reshape için
m.reshape(3,4)

ValueError: cannot reshape array of size 10 into shape (3,4)

In [ ]:
n=np.arange(1,13)
n

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
n.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

###-1 ile Boyuta Karar Vermek

In [ ]:
#otomatik olarak 4 kolonlu bir array yarattı
n.reshape(-1,4) #n.size = 12 olacak şekilde 4 sütun u olan array yapar

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

###Yeni Boyut Ekleme

In [ ]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a[np.newaxis, :] # : hepsini al demek, 1 row 10 column oldu

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [ ]:
#column vector
a[:, np.newaxis] # 10 row 1 column oldu

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [ ]:
a[:, np.newaxis].shape

(10, 1)

### Concatenation: **np.concatenate()**

In [ ]:
x= np.array([1,2,3])
y= np.array([4,5,6])

In [ ]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [ ]:
l=[9,0]

In [ ]:
np.concatenate([y,x,l])

NameError: name 'l' is not defined

In [ ]:
k = [10,11.2]
np.concatenate([y,x,k]) # bir tane float oldugundan elemanların hepsi float oldu

array([ 4. ,  5. ,  6. ,  1. ,  2. ,  3. , 10. , 11.2])

In [ ]:
m = ("a", 2) #list yerine tuple da kullanılabilir
np.concatenate([x,y,m]) # data tipi string e dönüştü

array(['1', '2', '3', '4', '5', '6', 'a', '2'], dtype='<U21')

###Size Mismatch

In [ ]:
b = np.array([1,2,3,4])
b

array([1, 2, 3, 4])

In [ ]:
# iki boyutlu

a= np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a.size

6

In [ ]:
a.ndim

2

In [ ]:
a.shape

(2, 3)

In [ ]:
b.shape #row column yok, 4 elemanı var dimension 1 dir. Row column dan bahsedebilmek için 2 boyutlu olması gerekir

(4,)

In [ ]:
#shape mismatch
np.concatenate([a,b])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [ ]:
#dimensionların aynı olması gerekir
m= np.concatenate([a,a])
m

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
#asis = 0 satır boyunca
m= np.concatenate([a,a],axis=0)
m

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
#axis= 1 sutun boyunca işlem
m= np.concatenate([a,a],axis=1)
m

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [ ]:
array_1 = np.array([[1,2,3],[0,0,0]])
array_2 = np.array([[0,0,0],[7,8,9]])

np.concatenate((array_1, array_2), axis = 1)


array([[1, 2, 3, 0, 0, 0],
       [0, 0, 0, 7, 8, 9]])

##Stack

Stack mantığını yeni dimension ekleyip o dimension üzerinde concatenation yaparak da sağlayabiliriz. Stack ile yaptığımız işlemi birleştirmek istediğimiz arraylere dimension ekledikten sonra concatenation ile de yapabiliriz.

In [ ]:
array_1 = np.array([1,2,3,4])

In [ ]:
array_2 = np.array([5,6,7,8])

In [ ]:
array_1

array([1, 2, 3, 4])

In [ ]:
array_2

array([5, 6, 7, 8])

In [ ]:
array_1.shape

(4,)

In [ ]:
array_2.shape

(4,)

In [ ]:
np.stack([array_1,array_2]) #axis yok çünkü row ve column yok. Yeni bir dimension yaratıp onun üzerie ekleme yapıyor

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
np.stack([array_1,array_2]).shape

(2, 4)

In [ ]:
np.stack([array_1,array_2],axis=1)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

# Splitting

In [ ]:
l=[10,20,30,40,50,60,70,80] #list

In [ ]:
l[0:5]

[10, 20, 30, 40, 50]

In [ ]:
l[:5]

[10, 20, 30, 40, 50]

In [ ]:
final=np.split(l, [2,5]) # l listesini 0-2, 2-5, kalan şeklinde böl.
final

[array([10, 20]), array([30, 40, 50]), array([60, 70, 80])]

In [ ]:
np.split(l, [2,6])#index 2 nin başına ve 6 nın başından böl: [0,2],[2,6][6,]

[array([10, 20]), array([30, 40, 50, 60]), array([70, 80])]

###Split'in Sonucunu Birden Çok Değişkene Eşitleme

In [ ]:
a,b =(1,10)

In [ ]:
print(a)
print(b)

1
10


In [ ]:
a,b,c=np.split(l,[2,6] )

In [ ]:
a

array([10, 20])

In [ ]:
b

array([30, 40, 50])

In [ ]:
c

array([60, 70, 80])

In [ ]:
type(np.split(l, [2,6])) # output genel olarak python list olarak tutuluyor

list

In [ ]:
type(np.split(l, [2,6])[0]) # elemanlar numpy array i olarak tutuluyor

numpy.ndarray

# Array elemanlarına erişmek

In [ ]:
a=np.arange(1,13).reshape(3,4)
a

In [ ]:
#birinci satır
a[0]

array([1, 2, 3, 4])

In [ ]:
# ikinci satır
a[1]

array([5, 6, 7, 8])

In [ ]:
#0.satır 0.kolon
a[0][0]

np.int64(1)

In [ ]:
#0.satır 1.kolon
a[0,1]

np.int64(2)

In [ ]:
a[1,1]

np.int64(6)

In [ ]:
#2.satır 2.kolon
a[2,2]

np.int64(11)

In [ ]:
#2.satır 2.kolon 300 olarak değiştirildi
a[2,2]= 300
a

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10, 300,  12]])

**vsplit**

Row' a göre ayrım yapıyor.

In [ ]:
a = np.arange(20).reshape(5,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
np.vsplit(a, [1])

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [ ]:
np.vsplit(a, [1])[0]

array([[0, 1, 2, 3]])

In [ ]:
np.vsplit(a, [1,3])

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

###**hsplit**

Column' a göre parçalar

In [ ]:
a = np.arange(20).reshape(2,10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [ ]:
np.hsplit(a, [2])

[array([[ 0,  1],
        [10, 11]]),
 array([[ 2,  3,  4,  5,  6,  7,  8,  9],
        [12, 13, 14, 15, 16, 17, 18, 19]])]

In [ ]:
np.hsplit(a, [2])[1]

array([[ 2,  3,  4,  5,  6,  7,  8,  9],
       [12, 13, 14, 15, 16, 17, 18, 19]])

In [ ]:
np.hsplit(a, [2])[1].shape

(2, 8)

In [ ]:
x, y = np.hsplit(a, [2])

In [ ]:
print(x)


[[ 0  1]
 [10 11]]


In [ ]:
print(y)

[[ 2  3  4  5  6  7  8  9]
 [12 13 14 15 16 17 18 19]]


In [ ]:
x, y, z = np.hsplit(a, [2,4]) #sütunları numaralandır. 2.index öncesine çentik at 4.index öncesine çentik at

In [ ]:
print(x)

[[ 0  1]
 [10 11]]


In [ ]:
print(y)

[[ 2  3]
 [12 13]]


In [ ]:
print(z)

[[ 4  5  6  7  8  9]
 [14 15 16 17 18 19]]


### Slice indeksing

In [5]:
a=np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a[0,0] #0.indexli row 0.columndaki eleman

np.int64(1)

In [ ]:
a[0][0]#0.indexli row 0.column

np.int64(1)

In [ ]:
# 0 satırı ile 2. satır arasındaki satırları yazdı. (2.satır dahil değil)
a[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
a[:1] #1.indexli row a kadar al

array([[1, 2, 3, 4]])

In [ ]:
#selects the first row of the array then selects the element at index 0 (the first element) from the selected row.
a[:1,0]

array([1])

In [ ]:
a[:] # bütün satır ve sütünu alır

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
#bütün satırları al ama 2.indexteki kolonu al
a[:,2]

array([ 3,  7, 11])

In [ ]:
a[:,2].shape # sayı öbeği olarak döndürdü

(3,)

In [ ]:
a[1,:]

array([5, 6, 7, 8])

In [8]:
a[:2,:3]

array([[1, 2, 3],
       [5, 6, 7]])

In [ ]:
#bütün satırları al ama 0'dan 2. kolona kadar olan sütünları al
a[:,0:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [ ]:
a[0,2:4]#0.row un 2-4. index aralığındaki columnu

array([3, 4])

In [ ]:
a[0:2,0:2]

array([[1, 2],
       [5, 6]])

In [ ]:
#bütün satırları ve bütün kolonlaru al
a[:,:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a[0:2,2] #row column mantığı yok sayı öbeği döndürür

array([3, 7])

In [6]:
a[0:2,2].shape # sayı öbeği döndürdü

(2,)

In [ ]:
a[::2,3]


array([ 4, 12])

In [ ]:
a[::,2]

array([ 3,  7, 11])

In [ ]:
a[::2]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [ ]:
a[1,1] = 10 # elemanı değiştirme. [1][1]indexdeki değer değişti
a

array([[ 1,  2,  3,  4],
       [ 5, 10,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
#Array'in veri tipi neyse ona cast olur, array in veri tipini dönüştürmez
a[1][1] = 20.4 # sadece int kısmı alınır
a

array([[ 1,  2,  3,  4],
       [ 5, 20,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a[1][1] = "21" # str int a cast oldu
a

array([[ 1,  2,  3,  4],
       [ 5, 21,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a[1][1] = "21.4"
a

ValueError: invalid literal for int() with base 10: '21.4'

In [ ]:
a[1][1] = "a"
a

ValueError: invalid literal for int() with base 10: 'a'

###Fancy Indexing

Birkaç tane belirli indexteki elemanı döndürür. İstediğin idndexteki elemanları seçersin

In [2]:
x = np.arange(1,15)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [3]:
wanted_idxs = [4,5,7,11] #4. 5. 7. ve 11. indexteki elemanları döndürür
x[wanted_idxs]

array([ 5,  6,  8, 12])

In [9]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
a[0, [1,3]] # 0. indexteki row u al ve 1. ile 3. indexteki columu al

array([1, 3])

In [12]:
a[0, [1,3]].shape # sayı öbeği olarak döner

(2,)

In [11]:
a[0, [1,3]].ndim

1

In [13]:
a[0:, [1,3]] #tüm row lara bak ve 1. ile 3. column u al

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [15]:
a[:, [1,3]] # 0 yazmana gerek yok zaten default

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [19]:
idx1 = [0,1,2] # bu indexleri al-> row olacak
idx2 = [0,1,3] #bu indexleri al -> column
a[idx1,idx2] #Fancy index virgülle olur, row column indexleri olarak seçildi

array([ 0,  5, 11])

In [20]:
a[idx1][idx2] # bu şekilde row ve column seçilmiyor

IndexError: index 3 is out of bounds for axis 0 with size 3

**Fancy indexing sonucunu belirli değerlere eşitlemek**

In [21]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
x[[1,2,3]] = 20
x

array([ 1, 20, 20, 20,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [28]:
x[[1,2,3]] = [100,200,300]
x

array([  1, 100, 200, 300,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14])

In [35]:
a=np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [39]:
b=a[1,1:3] #index 1 deki row ile 1. dahil 3. dahil olmayan column
b

array([6, 7])

In [42]:
b=a[1,[1,3]] # fancy indexing, Correct usage
b

array([6, 8])

In [36]:
# Do NOT use this one, it is tuple not fancy indexin
b=a[1,(1,3)] #Tuple olarak verilmiş, hatalı kullanımdır index 1 deki row ve 1. ile 3. indexteki columndak elemanlar
b

array([6, 8])

##**Sorting**

In [ ]:
array1= np.array([20,32,5,30,10])
array1

array([20, 32,  5, 30, 10])

In [ ]:
np.sort(array1) # array in değeri güncellenmez

array([ 5, 10, 20, 30, 32])

In [ ]:
array1

array([20, 32,  5, 30, 10])

In [ ]:
# array i sort edilmiş şeklinde güncellemek için
array1.sort()
array1

array([ 5, 10, 20, 30, 32])

###**argsort**

Sıraladıktan sonra indexleri döndürür

In [ ]:
array2= np.array([3,1,6,7,2])
array2

array([3, 1, 6, 7, 2])

In [ ]:
#küçükten büyüğe sıralayıp elemanların indexini döndürür
idxs = np.argsort(array2)
idxs

array([1, 4, 0, 2, 3])

##**Subarray**

In [43]:
a = np.arange(1,21).reshape(4,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [44]:
b = a[:2, :3]
b

array([[1, 2, 3],
       [6, 7, 8]])

In [45]:
b.ndim

2

In [46]:
b[0,0] = 100 #when we change the b's element
b

array([[100,   2,   3],
       [  6,   7,   8]])

In [47]:
a #a's element also changed, they use same memory

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20]])

##**Copy**

Subarray ed aynı memory adresi kullanıldığı için bu yöntemle ilk array i değiştirmeden işlem yapılır.

In [51]:
a = np.arange(1,21).reshape(4,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [52]:
c = a[:2, :3].copy()
c

array([[1, 2, 3],
       [6, 7, 8]])

In [53]:
c[0,0]= 100 # c array i değişti
c

array([[100,   2,   3],
       [  6,   7,   8]])

In [55]:
a # bu sefer a arrayi değişmedi

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

###**Conditional Indexing**

# filter

In [3]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
a < 7

array([ True,  True,  True,  True, False, False, False, False, False])

In [6]:
# 7 den küçük değerlere ulaştık
a[a<7]

array([1, 2, 3, 4, 5, 6])

In [8]:
filt= a < 5

In [9]:
filt

array([ True,  True,  True,  True, False, False, False, False, False])

In [10]:
a[filt]

array([1, 2, 3, 4])

In [ ]:
#array tipinde and = &
filt= (a>5) & (a<9)

In [ ]:
a[filt]

array([6, 7, 8])

In [ ]:
#array tipinde or = |
filt= (a<5) | (a>8)

In [ ]:
a[filt]

array([1, 2, 3, 4, 9])

In [ ]:
#filtrenin değili (a<5 dışında kalanlar)
filt= ~(a<5)

In [ ]:
a[filt]

array([5, 6, 7, 8, 9])

In [25]:
c = np.array([2,3,3,4,5,24,25,26,6])
c

array([ 2,  3,  3,  4,  5, 24, 25, 26,  6])

In [26]:
a == c #indexlerdeki sayılar aynı mı

array([False, False,  True,  True,  True, False, False, False, False])

In [27]:
a[a==c] # hangi değerlerde aynı indexlerdeler

array([3, 4, 5])

In [28]:
#broadcasting
a == [1]

array([ True, False, False, False, False, False, False, False, False])

In [29]:
a == 1

array([ True, False, False, False, False, False, False, False, False])

In [34]:
filt = (a < 3) | (a > 5)
filt

array([ True,  True, False, False, False,  True,  True,  True,  True])

In [33]:
a[filt]

array([1, 2, 6, 7, 8, 9])

In [36]:
a[(a > 3) & (a <= 5)]

array([4, 5])

In [11]:
b=np.arange(1,10).reshape(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
b<7

array([[ True,  True,  True],
       [ True,  True,  True],
       [False, False, False]])

In [13]:
#filtre boyutu bozar. istenirse sonra tekrardan boyut eklenebilir.
b[b<7]

array([1, 2, 3, 4, 5, 6])

In [ ]:
b[b<7].reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# 7 den küçük elamanlar ile oluşturulan altküme bir array
x= b[b<7].reshape(2,3)

In [ ]:
x

array([[1, 2, 3],
       [4, 5, 6]])

###Filtrenin Değili: **~**


In [37]:
a=np.arange(1,21).reshape(4,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [42]:
filt = a < 5
filt

array([[ True,  True,  True,  True, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [43]:
a[filt]

array([1, 2, 3, 4])

In [39]:
filt = ~((a > 5) & (a < 9))
filt

array([[ True,  True,  True,  True,  True],
       [False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [40]:
a[filt]

array([ 1,  2,  3,  4,  5,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

###Multidimensional Array'lerde Conditional Indexing

In [44]:
a=np.arange(1,21).reshape(4,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [45]:
type(a) # n dimensional array

numpy.ndarray

In [46]:
a < 7

array([[ True,  True,  True,  True,  True],
       [ True, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [47]:
type(a < 7) # n-dimensional array

numpy.ndarray

In [48]:
a[a < 7]

array([1, 2, 3, 4, 5, 6])

In [50]:
a[a<7].shape #sayı öbeği

(6,)

In [51]:
a = np.array([1,2,3,None], dtype=object)

In [52]:
a == None # None şeklinde verilenler filtrelenebilir

array([False, False, False,  True])

In [53]:
a[a==None]

array([None], dtype=object)

# SUM

In [54]:
b=np.arange(1,10).reshape(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#bütün elemanları topluyor.
print(np.sum(b))

45


In [56]:
filt = b < 5

In [58]:
filt

array([[ True,  True,  True],
       [ True, False, False],
       [False, False, False]])

In [59]:
b[filt]

array([1, 2, 3, 4])

In [57]:
np.sum(filt) #filtreye uyan kaç tane eleman var

np.int64(4)

In [60]:
np.sum(b[filt])# 1+2+3+4

np.int64(10)

In [ ]:
#7'den küçük olanların toplamı
np.sum(b[b<7])

np.int64(21)

In [61]:
filt2= ~((b > 5) & (b < 9))
filt2

array([[ True,  True,  True],
       [ True,  True, False],
       [False, False,  True]])

In [63]:
np.sum(filt2) # kaç eleman var

np.int64(6)

In [64]:
np.sum(b[filt2])#elemanların toplamı

np.int64(24)

###Belirli Axis Üzeride Toplama

In [66]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
# sütunların toplamı
# aslında her bir satırın ilk elemanlarını alıp topluyorsun
np.sum(b,axis=0)

(3,)

In [65]:
# satırların toplamı
#her bir sütunun ilk elemanlarını alıp topluyorsun
np.sum(b,axis=1)

array([ 6, 15, 24])

In [70]:
np.sum(b,axis=0).shape


(3,)

In [71]:
np.sum(b,axis=1).shape

(3,)

In [67]:
np.sum(b)

np.int64(45)

##All

Tüm elemanlar verilen şartı sağlıyor mu kontrol edilir.

In [72]:
a = np.arange(1,21).reshape(4,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [73]:
a > -1

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [75]:
np.all(a > -1)

np.True_

In [76]:
np.all(a > 5)

np.False_

In [77]:
np.all( a > 5, axis=0)

array([False, False, False, False, False])

In [78]:
np.all( a > 5, axis=1)

array([False,  True,  True,  True])

##**any()**

Herhangi bir eleman verilen sartı sağlıyor mu kontrol etmek

In [80]:
a = np.arange(20).reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [81]:
a > 17

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True,  True]])

In [82]:
np.any(a>17)

np.True_

In [83]:
np.any(a>17, axis= 0)

array([False, False, False,  True,  True])

In [84]:
np.any(a>17, axis= 1)

array([False, False, False,  True])