## NUMPY

Matematiksel fonksiyonların olduğu kütüphanedir. Hızlı numerik işlemler için kullanılır.


*   Tek boyutlu array olabilir ama matrix olamaz.
*   İki boyutlu array lere matrix denir.


*   Numpy Array ler homojen olmalı(aynı tipte veriler).
*  



In [3]:
import numpy as np

In [4]:
sinus = np.sin(np.pi/2)

## Array yaratmak


Python listlerine benzeyen, ancak farklı veri tiplerinde eleman içeremez aynı tipten çok sayıda elemanı içeren, hızlı işlem yapılmasını sağlayan kavramlardır.

In [5]:
x= np.array([1,2,3,4])

In [6]:
x

array([1, 2, 3, 4])

In [7]:
type(x)

numpy.ndarray

In [8]:
m= np.array(["a","b","c"])

In [9]:
m

array(['a', 'b', 'c'], dtype='<U1')

In [10]:
## eğer arrayin içinde bir tane bile karakter varsa; elemanlar, arrayın içinde string tipinde tutulur.
n= np.array([1,2,3,2.5,"a"])

In [11]:
n

array(['1', '2', '3', '2.5', 'a'], dtype='<U32')

In [12]:
# Bir tane float olduğu için dğer integerlar da floata dönüştü
z= np.array([1,2,3,3.5])

In [13]:
z

array([1. , 2. , 3. , 3.5])

In [14]:
# String değer içerdiğinden diğer elemanlar da string veri tipine cast edilir
c=np.array(['30',20,64,"s",6.2])
c

array(['30', '20', '64', 's', '6.2'], dtype='<U32')

## Array data tipini belirleme

In [15]:
x=np.array([1,2,3.4]) # veriler genel olana cast edilir integar lar float a döner

In [16]:
x

array([1. , 2. , 3.4])

In [93]:
x=np.array([1,2,3.6], dtype="int32")   #arrayin tipini integer yapma

In [94]:
x

array([1, 2, 3], dtype=int32)

In [19]:
y=np.array([1,2,3.4], dtype="str") #arrayin tipini str yapma

In [20]:
y

array(['1', '2', '3.4'], dtype='<U3')

In [21]:
y=np.array([1,2,"a"], dtype="int32")  #str olduğu için integer hale getiremeyiz.

ValueError: invalid literal for int() with base 10: 'a'

In [22]:
#String halinde yazılmış float floata cast edilebilir
z = np.array(["5.2"], dtype = "float")

In [23]:
z

array([5.2])

In [24]:
#String şeklinde yazılmış integer integar a cast edilebilir
z = np.array(["5"], dtype = "int32")

In [25]:
z

array([5], dtype=int32)

In [26]:
#String biçiminde yazılmış float direkt integer a cast edilemez
z = np.array(["5.2"], dtype = "int32")

ValueError: invalid literal for int() with base 10: '5.2'

## Elemanları 0 olan array

In [97]:
c= np.zeros(10) #kaç elemanlı 0 dan oluşan array istersin
c

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [95]:
np.zeros(10, dtype = str )

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U1')

# Elemanları 0 dan oluşan **multidimensional** array oluşturma

In [28]:
#3 satır(row) ve 5 sütun(kolon)
a=np.zeros((3,5)) #paranteze dikkat. Shape ve data type beklediği için () veya [] kullanmalısın

In [29]:
# 2 boyutlu 3x5 lik array = matris
x= np.zeros([3,5]) #köşeli paranteze dikkat
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [30]:
# 3 boyutlu = tensor
# 4 tane 5x7 lik array kur
y= np.zeros([4,5,7])
y

array([[[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]]])

In [98]:
np.zeros(2, dtype = int)

array([0, 0])

In [100]:
np.zeros((1,2), dtype = int) #Multidimensional array de data tipi belirtme

array([[0, 0]])

In [105]:
# four-dimensional NumPy array (tensor) filled with zeros
# 2 blocks, where each block contains 4 rows, 4 columns, and 5 elements in the innermost dimension
x=np.zeros([2,4,4,5])
x

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0

## array bilgilerine erişme

In [31]:
c.shape #boyutuna erişme

(10,)

In [32]:
c.ndim

1

In [33]:
a.shape

(3, 5)

In [34]:
a.ndim

2

In [35]:
x.shape

(3, 5)

In [36]:
y.shape

(4, 5, 7)

In [37]:
c.ndim

1

In [38]:
a.ndim

2

In [39]:
#boyut
x.ndim

2

In [40]:
#boyut
y.ndim

3

In [41]:
#array içindeki eleman (3*5)
x.size

15

In [42]:
# 4*5*7
y.size


140

## Belirtilen bir elemandan array oluşturma : **np.full()**

In [43]:
# 3x5 lik elemanları 7 olan array
np.full((3,5),7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [44]:
np.full((3,5),7, dtype="int32")

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]], dtype=int32)

In [45]:
np.full((3,5),"m")

array([['m', 'm', 'm', 'm', 'm'],
       ['m', 'm', 'm', 'm', 'm'],
       ['m', 'm', 'm', 'm', 'm']], dtype='<U1')

In [108]:
np.full((4,5), 5.6, dtype= "str") #5.2 önce integar a cast oluyor sonra string şeklinde dönüştürülüyor

array([['5', '5', '5', '5', '5'],
       ['5', '5', '5', '5', '5'],
       ['5', '5', '5', '5', '5'],
       ['5', '5', '5', '5', '5']], dtype='<U1')

In [109]:
np.full((4,5),"5.2")

array([['5.2', '5.2', '5.2', '5.2', '5.2'],
       ['5.2', '5.2', '5.2', '5.2', '5.2'],
       ['5.2', '5.2', '5.2', '5.2', '5.2'],
       ['5.2', '5.2', '5.2', '5.2', '5.2']], dtype='<U3')

In [110]:
np.full(2,3) # 1-dimensional array with 2 elements, each filled with the value 3.

array([3, 3])

### ardışık sayılardan array

In [46]:
np.arange(0,12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [47]:
np.arange(0,14,2) # 2 atlamalı şekilde 14'e kadar array oluşturdu

array([ 0,  2,  4,  6,  8, 10, 12])

## aralığı eşit uzaklıkta bölerek array oluşturma

verilen başlangıç ve bitiş noktasına göre, başlangıç ve bitiş noktası da dahil, aradaki sayıları eşit uzaklıkta olacak şekilde yazarak oluşturur. (linspace)

In [48]:
#default olarak aradaki mesafeyi 50 nokta olacak şekilde yazar
np.linspace(1,2)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [49]:
np.linspace(1,2).ndim

1

In [50]:
#num=3 ile 1-2 arasındaki mesafeyi kendileri dahil 3'e bölüyor.
np.linspace(1,2,num=3)

array([1. , 1.5, 2. ])

In [51]:
np.linspace(1.5,3, num=3)

array([1.5 , 2.25, 3.  ])

## Normal Dağılıma Uygun değerler ile array oluşturma

In [55]:
# np.random.normal(mean, std, array shape)

In [53]:
np.random.normal(0,1, (3,5)) #0 ortalamalı, standart sapması 1 olacak şekilde (3x5)lik
#bir normal dağılıma uygun array oluşturduk

array([[ 0.22753338,  0.61759578, -2.08359809,  0.36115503, -0.28057289],
       [-1.45751551,  0.12881301, -0.92069119,  1.71970581,  0.60201386],
       [ 0.22370532,  1.24464806, -0.1511746 ,  1.6987345 , -0.60388346]])

In [54]:
np.random.normal(0,100, (3,5))

array([[   1.34359502,   15.43204244, -119.19738755, -101.18570808,
        -207.78771138],
       [ 131.24975935,  -30.06219663, -143.52951783,   75.06859769,
        -137.99573634],
       [-146.83945202, -104.59524868,  133.31050658, -185.80177234,
          60.0273064 ]])

## Random olarak

In [56]:
# np.random.randint(low,high)
# 15 dahil değil

np.random.randint(1,15,(3,5))

array([[11,  1,  1,  4, 10],
       [ 5,  9,  5,  8,  7],
       [ 5,  2, 12, 14,  9]])

In [57]:

np.random.randint(5,15,(3,5))

array([[12,  8,  5,  7, 12],
       [ 9, 12,  9, 13, 11],
       [ 7, 14,  8,  9, 11]])

In [58]:
# birim array yaratma (köşegenleri 1 olan diğer elemanları 0 olan array)
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [59]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

# Array Matematiksel İşlemler

In [60]:
x= np.array([1,2,3])
y= np.array([4,5,6])

In [61]:
x

array([1, 2, 3])

In [62]:
x*y

array([ 4, 10, 18])

In [63]:
x+y

array([5, 7, 9])

In [64]:
print(x+y)

[5 7 9]


In [65]:
x= np.array([1,2,3])
y= np.array([4,5,6,8])

x*y  #(arraylar birbirine denk olmadığı için hata aldık)

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [66]:
#note: listede toplama işlemi tanımlı değil
[1,2,3] + [4,5,6]

[1, 2, 3, 4, 5, 6]

In [67]:
a= np.array([    [1,2,3],[4,5,6]      ])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
a.ndim

2

In [70]:
a.shape

(2, 3)

In [71]:
a*a

array([[ 1,  4,  9],
       [16, 25, 36]])

In [72]:
a+a

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [73]:
a/a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [74]:
a*3

array([[ 3,  6,  9],
       [12, 15, 18]])

In [75]:
a+5

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [76]:
#her bir değerin karekökünü aldı
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [77]:
#matris gibi çarpım yapar. (dot) (shapelerin aynı olmasına gerek yoktur)

a1 = np.array([[1,2],
               [2,0],
               [3,1]])

a2 = np.array ([[4,3],
                [1,2]])

print(np.dot(a1,a2))


[[ 6  7]
 [ 8  6]
 [13 11]]


## Reshape

In [78]:
m=np.arange(1,11)
m

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [79]:
m.reshape(2,5) # 2*5 = 10 olduğundan ve 10=m olduğundan hatasız çalışır

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [80]:
m.reshape(3,5) #3*5= 15 olduğundan 15 != m olduğundan hata aldık. Array 1 den 11 e kadar ayarlanmıştı.

ValueError: cannot reshape array of size 10 into shape (3,5)

In [81]:
# eleman sayısı ile reshape içindeki (satır * sütunun) aynısı olması gerekldiri reshape için
m.reshape(3,4)

ValueError: cannot reshape array of size 10 into shape (3,4)

In [82]:
n=np.arange(1,13)
n

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [83]:
n.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [84]:
#otomatik olarak 4 kolonlu bir array yarattı
n.reshape(-1,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# concatenate

In [85]:
x= np.array([1,2,3])
y= np.array([4,5,6])

In [86]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [87]:
l=[9,0]

In [88]:
np.concatenate([y,x,l])

array([4, 5, 6, 1, 2, 3, 9, 0])

In [ ]:
# iki boyutlu

a= np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [89]:
a.ndim

2

In [90]:
a.shape

(2, 3)

In [91]:
#dimensionların aynı olması gerekir
m= np.concatenate([a,a])
m

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
#asis = 0 satır boyunca
m= np.concatenate([a,a],axis=0)
m

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [92]:
#axis= 1 sutun boyunca işlem
m= np.concatenate([a,a],axis=1)
m

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# Splitting

In [ ]:
l=[10,20,30,40,50,60,70,80] #list

In [ ]:
l[0:5]

[10, 20, 30, 40, 50]

In [ ]:
l[:5]

[10, 20, 30, 40, 50]

In [2]:
final=np.split(l, [2,5]) # l listesini 0-2, 2-5, kalan şeklinde böl.
final

NameError: name 'np' is not defined

In [ ]:
a,b,c=final

In [1]:
a,b,c=np.split(l,[2,5] )

NameError: name 'np' is not defined

In [ ]:
a

array([10, 20])

In [ ]:
b

array([30, 40, 50])

In [ ]:
c

array([60, 70, 80])

# Array elemanlarına erişmek

In [ ]:
a=np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
#birinci satır
a[0]

array([1, 2, 3, 4])

In [ ]:
# ikinci satır
a[1]

array([5, 6, 7, 8])

In [ ]:
#0.satır 0.kolon
a[0][0]

np.int64(1)

In [ ]:
#0.satır 1.kolon
a[0,1]

np.int64(2)

In [ ]:
a[1,1]

np.int64(6)

In [ ]:
#2.satır 2.kolon
a[2,2]

np.int64(11)

In [ ]:
#2.satır 2.kolon 300 olarak değiştirildi
a[2,2]= 300
a

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10, 300,  12]])

### Slice indeksing

In [ ]:
a=np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# 0 satırı ile 2. satır arasındaki satırları yazdı. (2.satır dahil değil)
a[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
a[:1]

array([[1, 2, 3, 4]])

In [ ]:
#selects the first row of the array then selects the element at index 0 (the first element) from the selected row.
a[:1,0]

array([1])

In [ ]:
a[:] # bütün satır ve sütünu alır

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
#bütün satırları al ama 2.indexteki kolonu al
a[:,2]

array([ 3,  7, 11])

In [ ]:
#bütün satırları al ama 0'dan 2. kolona kadar olan sütünları al
a[:,0:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [ ]:
a[0:2,0:2]

array([[1, 2],
       [5, 6]])

In [ ]:
#bütün satırları ve bütün kolonlaru al
a[:,:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a[0:2,2]

array([3, 7])

# filter

In [ ]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a<7

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

In [ ]:
# 7 den küçük değerlere ulaştık
a[a<7]

array([1, 2, 3, 4, 5, 6])

In [ ]:
filt= a<5

In [ ]:
a[filt]

array([1, 2, 3, 4])

In [ ]:
#array tipinde and = &
filt= (a>5) & (a<9)

In [ ]:
a[filt]

array([6, 7, 8])

In [ ]:
#array tipinde or = |
filt= (a<5) | (a>8)

In [ ]:
a[filt]

array([1, 2, 3, 4, 9])

In [ ]:
#filtrenin değili (a<5 dışında kalanlar)
filt= ~(a<5)

In [ ]:
a[filt]

array([5, 6, 7, 8, 9])

In [ ]:
b=np.arange(1,10).reshape(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
b<7

array([[ True,  True,  True],
       [ True,  True,  True],
       [False, False, False]])

In [ ]:
#filtre boyutu bozar. istenirse sonra tekrardan boyut eklenebilir.
b[b<7]

array([1, 2, 3, 4, 5, 6])

In [ ]:
b[b<7].reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# 7 den küçük elamanlar ile oluşturulan altküme bir array
x= b[b<7].reshape(2,3)

In [ ]:
x

array([[1, 2, 3],
       [4, 5, 6]])

# SUM

In [ ]:
b=np.arange(1,10).reshape(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#bütün elemanları topluyor.
print(np.sum(b))

45


In [ ]:
#7'den küçük olanların toplamı
np.sum(b[b<7])

np.int64(21)

In [ ]:
# sütunların toplamı
# aslında her bir satırın ilk elemanlarını alıp topluyorsun
np.sum(b,axis=0)

array([12, 15, 18])

In [ ]:
# satırların toplamı
#her bir sütunun ilk elemanlarını alıp topluyorsun
np.sum(b,axis=1)

array([ 6, 15, 24])